In [1]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

In [7]:
data = pd.read_csv('/content/drive/MyDrive/Hyderabad-Data.csv')

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer

In [9]:
data.head()

,active,amenities,balconies,bathroom,combineDescription,completeStreetName,deposit,facing,facingDesc,floor,...,property_size,reactivationSource,rent_amount,sharedAccomodation,shortUrl,swimmingPool,totalFloor,type_bhk,waterSupply,weight
0,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",3,3,NaN,"Shreya carnation, Block I, NCB Enclave, Gachib...",90000,W,West,3,...,2200,USER_DASHBOARD,28000,False,http://nobr.kr/sv/9Kvqj,False,5,BHK3,CORP_BORE,NaN
1,True,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",1,2,NaN,"Inner Ring Rd, near RTO Bandlaguda South Zone",45000,E,East,2,...,1200,USER_DASHBOARD,15000,False,http://nobr.kr/sv/j2pD6,False,2,BHK3,BOREWELL,NaN
2,True,"{""LIFT"":true,""GYM"":true,""INTERNET"":false,""AC"":...",3,3,NaN,"Rd Number 2, Shirdi Sai Nagar, Manikonda, Hyde...",80000,E,East,0,...,1800,MISSED_CALL,16000,False,http://nobr.kr/sv/TXJmj,False,3,BHK3,CORP_BORE,NaN
3,True,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",1,2,NaN,"Plot No. 44, Road No. 1/A, kakatiya colony, LB...",18000,W,West,2,...,750,MISSED_CALL,9000,False,http://nobr.kr/sv/FnCsf,False,2,BHK2,CORP_BORE,NaN
4,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",2,2,NaN,"Madhapur HUDA Techno Enclave, Near MaxCure Su...",80000,E,East,2,...,1250,None,32500,False,http://nobr.kr/sv/BQFRb,False,5,BHK2,CORP_BORE,NaN

In [10]:
data.describe()

,bathroom,combineDescription,deposit,floor,property_age,property_size,rent_amount,totalFloor,weight
count,19110.000000,0.0,1.911000e+04,19110.000000,19110.000000,19110.000000,19110.000000,19110.000000,0.0
mean,1.911826,NaN,3.337933e+04,2.109158,3.782261,1067.674411,14919.719362,3.907902,NaN
std,0.764841,NaN,4.101519e+04,2.424864,3.461540,549.019152,9623.547307,3.899450,NaN
min,1.000000,NaN,1.000000e+00,0.000000,-1.000000,0.000000,0.000000,0.000000,NaN
25%,1.000000,NaN,1.600000e+04,1.000000,1.000000,700.000000,8999.000000,2.000000,NaN
50%,2.000000,NaN,2.500000e+04,2.000000,3.000000,1000.000000,12500.000000,3.000000,NaN
75%,2.000000,NaN,4.000000e+04,3.000000,5.000000,1334.000000,18000.000000,5.000000,NaN
max,14.000000,NaN,2.000000e+06,31.000000,15.000000,12000.000000,100000.000000,80.000000,NaN

In [11]:
# 1. Handling Missing Values
# Check for missing values
missing_values = data.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 active                    0
amenities                 0
balconies                 0
bathroom                  0
combineDescription    19110
completeStreetName        2
deposit                   0
facing                    0
facingDesc             9541
floor                     0
furnishingDesc            0
gym                       0
id                        0
isMaintenance             0
lift                      0
loanAvailable             0
locality                  6
localityId                0
location                  0
maintenanceAmount         0
ownerName                 0
parking                   0
parkingDesc               0
propertyTitle             0
propertyType              0
property_age              0
property_size             0
reactivationSource       63
rent_amount               0
sharedAccomodation        0
shortUrl                  0
swimmingPool              0
totalFloor                0
type_bhk                  0
waterSupply               0
weight                19110
dtype: int64

In [12]:
New_Data = data.drop(['active', 'amenities', 'balconies',
       'completeStreetName', 'facing', 'facingDesc',
        'id', 'isMaintenance', 'lift', 'loanAvailable',
         'ownerName',
       'reactivationSource',
        'shortUrl', 'swimmingPool',
        'weight','combineDescription',
                      'location',
],axis=1)

In [13]:
# after removing irrelevant columns
New_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19110 entries, 0 to 19109
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bathroom            19110 non-null  int64
 1   deposit             19110 non-null  int64
 2   floor               19110 non-null  int64
 3   furnishingDesc      19110 non-null  object
 4   gym                 19110 non-null  bool
 5   locality            19104 non-null  object
 6   localityId          19110 non-null  object
 7   maintenanceAmount   19110 non-null  object
 8   parking             19110 non-null  object
 9   parkingDesc         19110 non-null  object
 10  propertyTitle       19110 non-null  object
 11  propertyType        19110 non-null  object
 12  property_age        19110 non-null  int64
 13  property_size       19110 non-null  int64
 14  rent_amount         19110 non-null  int64
 15  sharedAccomodation  19110 non-null  bool
 16  totalFloor          19110 non-null  int64
 17  type_bhk            19110 non-null  object
 18  waterSupply         19110 non-null  object
dtypes: bool(2), int64(7), object(10)
memory usage: 2.5+ MB

In [14]:
# after removing irrelevant columns
New_Data.isnull().sum()

bathroom              0
deposit               0
floor                 0
furnishingDesc        0
gym                   0
locality              6
localityId            0
maintenanceAmount     0
parking               0
parkingDesc           0
propertyTitle         0
propertyType          0
property_age          0
property_size         0
rent_amount           0
sharedAccomodation    0
totalFloor            0
type_bhk              0
waterSupply           0
dtype: int64

In [15]:
# Fill missing values in the "locality" column with 0
New_Data['locality'].fillna(0, inplace=True)

# Check for missing values after filling
missing_values = New_Data.isnull().sum()

# Print the updated DataFrame with missing values filled
print(New_Data)

# Print the count of missing values in each column
print("Missing Values Count:\n", missing_values)

       bathroom  deposit  floor furnishingDesc    gym         locality  \
0             3    90000      3           Semi  False       Gachibowli
1             2    45000      2    Unfurnished  False  Chandrayangutta
2             3    80000      0           Semi   True        Manikonda
3             2    18000      2    Unfurnished  False         LB Nagar
4             2    80000      2           Semi  False       HITEC City
...         ...      ...    ...            ...    ...              ...
19105         1    17000      0    Unfurnished  False       Gachibowli
19106         2     8500      2    Unfurnished  False       Jillalguda
19107         3    30000      3    Unfurnished  False         Moosapet
19108         1    13000      3    Unfurnished  False       Kukatpally
19109         1    11000      1    Unfurnished  False    Santosh Nagar

                      localityId maintenanceAmount      parking   parkingDesc  \
0           gachibowli_hyderabad              2000         BOTH  Bike and Car
1      chandrayangutta_hyderabad              None  TWO_WHEELER          Bike
2            manikonda_hyderabad              1000         BOTH  Bike and Car
3                      NOT_FOUND               500         BOTH  Bike and Car
4          hitech_city_hyderabad              2000         BOTH  Bike and Car
...                          ...               ...          ...           ...
19105         rai_durg_hyderabad               500         BOTH  Bike and Car
19106                  NOT_FOUND               500         BOTH  Bike and Car
19107         moosapet_hyderabad              None         BOTH  Bike and Car
19108                  NOT_FOUND              None  TWO_WHEELER          Bike
19109    santosh_nagar_hyderabad              None  TWO_WHEELER          Bike

                                          propertyTitle propertyType  \
0        3 BHK For Rent in Shreya Carnation, Gachibowli         RENT
1                     3 BHK For Rent in Chandrayangutta         RENT
2           3 BHK For Rent in Amrutha Avenue, Manikonda         RENT
3               2 BHK For Rent in Standalone , Lb Nagar         RENT
4       2 BHK For Rent in Vibrant Residency, Hitec City         RENT
...                                                 ...          ...
19105  1 BHK For Rent in Chitrapuri Colony , Gachibowli         RENT
19106                      2 BHK For Rent in Jillalguda         RENT
19107                       2 BHK For Rent in  Moosapet         RENT
19108                      1 BHK For Rent in Kukatpally         RENT
19109                   1 BHK For Rent in Santosh Nagar         RENT

       property_age  property_size  rent_amount  sharedAccomodation  \
0                 5           2200        28000               False
1                 1           1200        15000               False
2                 0           1800        16000               False
3                 0            750         9000               False
4                 5           1250        32500               False
...             ...            ...          ...                 ...
19105             3            500         8500               False
19106             3            900         8500               False
19107             5           1150        15000               False
19108             3            500         7000               False
19109             5            400         5500               False

       totalFloor type_bhk waterSupply
0               5     BHK3   CORP_BORE
1               2     BHK3    BOREWELL
2               3     BHK3   CORP_BORE
3               2     BHK2   CORP_BORE
4               5     BHK2   CORP_BORE
...           ...      ...         ...
19105           5     BHK1        None
19106           4     BHK2    BOREWELL
19107           3     BHK2        None
19108           3     BHK1        None
19109           1     BHK1        None

[19110 rows x 19 columns]
Missing Values Count:
 bathroom              0
deposit               0
floor                 0
furnishingDesc        0
gym                   0
locality              0
localityId            0
maintenanceAmount     0
parking               0
parkingDesc           0
propertyTitle         0
propertyType          0
property_age          0
property_size         0
rent_amount           0
sharedAccomodation    0
totalFloor            0
type_bhk              0
waterSupply           0
dtype: int64

In [16]:
New_Data.isnull().sum()

bathroom              0
deposit               0
floor                 0
furnishingDesc        0
gym                   0
locality              0
localityId            0
maintenanceAmount     0
parking               0
parkingDesc           0
propertyTitle         0
propertyType          0
property_age          0
property_size         0
rent_amount           0
sharedAccomodation    0
totalFloor            0
type_bhk              0
waterSupply           0
dtype: int64

In [17]:
New_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19110 entries, 0 to 19109
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bathroom            19110 non-null  int64
 1   deposit             19110 non-null  int64
 2   floor               19110 non-null  int64
 3   furnishingDesc      19110 non-null  object
 4   gym                 19110 non-null  bool
 5   locality            19110 non-null  object
 6   localityId          19110 non-null  object
 7   maintenanceAmount   19110 non-null  object
 8   parking             19110 non-null  object
 9   parkingDesc         19110 non-null  object
 10  propertyTitle       19110 non-null  object
 11  propertyType        19110 non-null  object
 12  property_age        19110 non-null  int64
 13  property_size       19110 non-null  int64
 14  rent_amount         19110 non-null  int64
 15  sharedAccomodation  19110 non-null  bool
 16  totalFloor          19110 non-null  int64
 17  type_bhk            19110 non-null  object
 18  waterSupply         19110 non-null  object
dtypes: bool(2), int64(7), object(10)
memory usage: 2.5+ MB

In [18]:
#one-hot encoding for these categorical columns
New_Data = pd.get_dummies(New_Data, columns=['furnishingDesc', 'locality', 'localityId', 'maintenanceAmount', 'parking', 'parkingDesc', 'propertyTitle', 'propertyType', 'type_bhk', 'waterSupply'])

In [19]:
New_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19110 entries, 0 to 19109
Columns: 13981 entries, bathroom to waterSupply_None
dtypes: bool(2), int64(7), uint8(13972)
memory usage: 255.7 MB

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_columns = ['bathroom', 'deposit', 'floor', 'property_age', 'property_size', 'totalFloor', 'rent_amount']

New_Data[numerical_columns] = scaler.fit_transform(New_Data[numerical_columns])

In [21]:
New_Data.head()

,bathroom,deposit,floor,gym,property_age,property_size,rent_amount,sharedAccomodation,totalFloor,furnishingDesc_Full,...,type_bhk_BHK1,type_bhk_BHK2,type_bhk_BHK3,type_bhk_BHK4,type_bhk_BHK4PLUS,type_bhk_RK1,waterSupply_BOREWELL,waterSupply_CORPORATION,waterSupply_CORP_BORE,waterSupply_None
0,1.422782,1.380517,0.367388,False,0.351800,2.062506,1.359231,False,0.280072,0,...,0,0,1,0,0,0,0,0,1,0
1,0.115287,0.283333,-0.045017,False,-0.803785,0.241028,0.008342,False,-0.489287,0,...,0,0,1,0,0,0,1,0,0,0
2,1.422782,1.136698,-0.869827,True,-1.092681,1.333915,0.112257,False,-0.232834,0,...,0,0,1,0,0,0,0,0,1,0
3,0.115287,-0.374977,-0.045017,False,-1.092681,-0.578637,-0.615145,False,-0.489287,0,...,0,1,0,0,0,0,0,0,1,0
4,0.115287,1.136698,-0.045017,False,0.351800,0.332102,1.826846,False,0.280072,0,...,0,1,0,0,0,0,0,0,1,0

In [22]:
#Split your dataset into a training set and a testing set
from sklearn.model_selection import train_test_split

# Split the data into features (X) and the target variable (y)
X = New_Data.drop('rent_amount', axis=1)
y = New_Data['rent_amount']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
# Create a Linear Regression model
model = LinearRegression()

In [ ]:
# Train the model on the training data
model.fit(X_train, y_train)